// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request for
/// [ReservationService.CreateCapacityCommitment][google.cloud.bigquery.reservation.v1.ReservationService.CreateCapacityCommitment].
///
/// [google.cloud.bigquery.reservation.v1.ReservationService.CreateCapacityCommitment]: <doc:ReservationServiceClient/createCapacityCommitment(request:options:)>
public struct CreateCapacityCommitmentRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Resource name of the parent reservation. E.g.,
  ///    `projects/myproject/locations/US`
  public var parent: Swift.String = Swift.String()

  /// Content of the capacity commitment to create.
  public var capacityCommitment: CapacityCommitment? = nil

  /// If true, fail the request if another project in the organization has a
  /// capacity commitment.
  public var enforceSingleAdminProjectPerOrg: Swift.Bool = Swift.Bool()

  /// The optional capacity commitment ID. Capacity commitment name will be
  /// generated automatically if this field is empty.
  /// This field must only contain lower case alphanumeric characters or dashes.
  /// The first and last character cannot be a dash. Max length is 64 characters.
  /// NOTE: this ID won't be kept if the capacity commitment is split or merged.
  public var capacityCommitmentId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateCapacityCommitmentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateCapacityCommitmentRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.bigquery.reservation.v1.CreateCapacityCommitmentRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
