// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ReservationServiceStub: Sendable {
    func createReservation(
      request: CreateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    func listReservations(
      request: ListReservationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse

    func getReservation(
      request: GetReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    func deleteReservation(
      request: DeleteReservationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func updateReservation(
      request: UpdateReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    func failoverReservation(
      request: FailoverReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation

    func createCapacityCommitment(
      request: CreateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    func listCapacityCommitments(
      request: ListCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse

    func getCapacityCommitment(
      request: GetCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    func deleteCapacityCommitment(
      request: DeleteCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws

    func updateCapacityCommitment(
      request: UpdateCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    func splitCapacityCommitment(
      request: SplitCapacityCommitmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse

    func mergeCapacityCommitments(
      request: MergeCapacityCommitmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment

    func createAssignment(
      request: CreateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    func listAssignments(
      request: ListAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse

    func deleteAssignment(
      request: DeleteAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws

    func searchAssignments(
      request: SearchAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse

    func searchAllAssignments(
      request: SearchAllAssignmentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse

    func moveAssignment(
      request: MoveAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    func updateAssignment(
      request: UpdateAssignmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment

    func getBiReservation(
      request: GetBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation

    func updateBiReservation(
      request: UpdateBiReservationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func createReservationGroup(
      request: CreateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup

    func getReservationGroup(
      request: GetReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup

    func deleteReservationGroup(
      request: DeleteReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listReservationGroups(
      request: ListReservationGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse

    func updateReservationGroup(
      request: UpdateReservationGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup
  }
}
