// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleIAMV1
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ReservationServiceLogging: ReservationServiceStub {
    let inner: any ReservationServiceStub
    let logger: Logger

    public init(_ inner: any ReservationServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-bigquery-reservation-v1"
      logger[metadataKey: "gcp.client.service"] = "bigqueryreservation"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ReservationService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createReservation(
      request: CreateReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createReservation",
        action: {
          (r: CreateReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.createReservation(request: r, options: o)
        })
    }

    public func listReservations(
      request: ListReservationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReservations",
        action: {
          (r: ListReservationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListReservationsResponse
          in
          return try await self.inner.listReservations(request: r, options: o)
        })
    }

    public func getReservation(
      request: GetReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReservation",
        action: {
          (r: GetReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.getReservation(request: r, options: o)
        })
    }

    public func deleteReservation(
      request: DeleteReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteReservation",
        action: {
          (r: DeleteReservationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteReservation(request: r, options: o)
        })
    }

    public func updateReservation(
      request: UpdateReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateReservation",
        action: {
          (r: UpdateReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.updateReservation(request: r, options: o)
        })
    }

    public func failoverReservation(
      request: FailoverReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Reservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "failoverReservation",
        action: {
          (r: FailoverReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Reservation
          in
          return try await self.inner.failoverReservation(request: r, options: o)
        })
    }

    public func createCapacityCommitment(
      request: CreateCapacityCommitmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCapacityCommitment",
        action: {
          (r: CreateCapacityCommitmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.createCapacityCommitment(request: r, options: o)
        })
    }

    public func listCapacityCommitments(
      request: ListCapacityCommitmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCapacityCommitments",
        action: {
          (r: ListCapacityCommitmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListCapacityCommitmentsResponse
          in
          return try await self.inner.listCapacityCommitments(request: r, options: o)
        })
    }

    public func getCapacityCommitment(
      request: GetCapacityCommitmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCapacityCommitment",
        action: {
          (r: GetCapacityCommitmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.getCapacityCommitment(request: r, options: o)
        })
    }

    public func deleteCapacityCommitment(
      request: DeleteCapacityCommitmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCapacityCommitment",
        action: {
          (r: DeleteCapacityCommitmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteCapacityCommitment(request: r, options: o)
        })
    }

    public func updateCapacityCommitment(
      request: UpdateCapacityCommitmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCapacityCommitment",
        action: {
          (r: UpdateCapacityCommitmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.updateCapacityCommitment(request: r, options: o)
        })
    }

    public func splitCapacityCommitment(
      request: SplitCapacityCommitmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "splitCapacityCommitment",
        action: {
          (r: SplitCapacityCommitmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SplitCapacityCommitmentResponse
          in
          return try await self.inner.splitCapacityCommitment(request: r, options: o)
        })
    }

    public func mergeCapacityCommitments(
      request: MergeCapacityCommitmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.CapacityCommitment {
      try await self._intercept(
        request: request,
        options: options,
        name: "mergeCapacityCommitments",
        action: {
          (r: MergeCapacityCommitmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.CapacityCommitment
          in
          return try await self.inner.mergeCapacityCommitments(request: r, options: o)
        })
    }

    public func createAssignment(
      request: CreateAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAssignment",
        action: {
          (r: CreateAssignmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.createAssignment(request: r, options: o)
        })
    }

    public func listAssignments(
      request: ListAssignmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListAssignmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAssignments",
        action: {
          (r: ListAssignmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListAssignmentsResponse
          in
          return try await self.inner.listAssignments(request: r, options: o)
        })
    }

    public func deleteAssignment(
      request: DeleteAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAssignment",
        action: {
          (r: DeleteAssignmentRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAssignment(request: r, options: o)
        })
    }

    public func searchAssignments(
      request: SearchAssignmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAssignmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchAssignments",
        action: {
          (r: SearchAssignmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SearchAssignmentsResponse
          in
          return try await self.inner.searchAssignments(request: r, options: o)
        })
    }

    public func searchAllAssignments(
      request: SearchAllAssignmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchAllAssignments",
        action: {
          (r: SearchAllAssignmentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.SearchAllAssignmentsResponse
          in
          return try await self.inner.searchAllAssignments(request: r, options: o)
        })
    }

    public func moveAssignment(
      request: MoveAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      try await self._intercept(
        request: request,
        options: options,
        name: "moveAssignment",
        action: {
          (r: MoveAssignmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.moveAssignment(request: r, options: o)
        })
    }

    public func updateAssignment(
      request: UpdateAssignmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.Assignment {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAssignment",
        action: {
          (r: UpdateAssignmentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.Assignment
          in
          return try await self.inner.updateAssignment(request: r, options: o)
        })
    }

    public func getBiReservation(
      request: GetBiReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBiReservation",
        action: {
          (r: GetBiReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.BiReservation
          in
          return try await self.inner.getBiReservation(request: r, options: o)
        })
    }

    public func updateBiReservation(
      request: UpdateBiReservationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.BiReservation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBiReservation",
        action: {
          (r: UpdateBiReservationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.BiReservation
          in
          return try await self.inner.updateBiReservation(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func createReservationGroup(
      request: CreateReservationGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "createReservationGroup",
        action: {
          (r: CreateReservationGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.createReservationGroup(request: r, options: o)
        })
    }

    public func getReservationGroup(
      request: GetReservationGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReservationGroup",
        action: {
          (r: GetReservationGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.getReservationGroup(request: r, options: o)
        })
    }

    public func deleteReservationGroup(
      request: DeleteReservationGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteReservationGroup",
        action: {
          (r: DeleteReservationGroupRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteReservationGroup(request: r, options: o)
        })
    }

    public func listReservationGroups(
      request: ListReservationGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ListReservationGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReservationGroups",
        action: {
          (r: ListReservationGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ListReservationGroupsResponse
          in
          return try await self.inner.listReservationGroups(request: r, options: o)
        })
    }

    public func updateReservationGroup(
      request: UpdateReservationGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryReservationV1.ReservationGroup {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateReservationGroup",
        action: {
          (r: UpdateReservationGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryReservationV1.ReservationGroup
          in
          return try await self.inner.updateReservationGroup(request: r, options: o)
        })
    }
  }
}
