// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A reservation group is a container for reservations.
public struct ReservationGroup: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the reservation group, e.g.,
  /// `projects/*/locations/*/reservationGroups/team1-prod`.
  /// The reservation_group_id must only contain lower case alphanumeric
  /// characters or dashes. It must start with a letter and must not end with a
  /// dash. Its maximum length is 64 characters.
  public var name: Swift.String = Swift.String()

  /// Optional. The parent reservation group of the reservation group.
  /// Format: `projects/*/locations/*/reservationGroups/team1-prod` for non-root
  /// reservation groups, or `projects/*/locations/*` for root reservation
  /// groups.
  public var parentGroup: Swift.String = Swift.String()

  /// Output only. Creation time of the reservation group.
  public var creationTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Last update time of the reservation group via a user
  /// operation. This timestamp is updated only when an update operation
  /// explicitly targets this reservation group directly. It is not updated when
  /// parent or child groups are created, updated, or deleted.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Initialize a new instance of `ReservationGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReservationGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.reservation.v1.ReservationGroup"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
